### ISSUE TITLE
Error in Python 3.5

### ISSUE THREAD

**Issue by theblackturtle** [countercept/python-exe-unpacker#2]
Hi, Is it work with python 3.5? I ran "python_exe_unpack.py" to decompile *.exe file which is write in python 3.5 too. Then I got this error.
```
[*] On Python 3.5
[*] Processing CLI.exe
[*] Pyinstaller version: 2.1+
[*] This exe is packed using pyinstaller
[*] Unpacking the binary now
[*] Python version: 35
[*] Length of package: 40426154 bytes
[*] Found 110 files in CArchive
Traceback (most recent call last):
  File "python_exe_unpack.py", line 381, in <module>
    main()
  File "python_exe_unpack.py", line 364, in main
    pyinstaller.unpacked(file_name)
  File "python_exe_unpack.py", line 243, in unpacked
    self.__pyinstxtractor_extract()
  File "python_exe_unpack.py", line 237, in __pyinstxtractor_extract
    self.py_inst_archive.extractFiles(self.extraction_dir)
TypeError: extractFiles() takes 1 positional argument but 2 were given
```
I tried to use pyinstxtractor.py too, I can extract but can not decompile from pyc to py ( I already decrypted *_encrypt with key). Please tell me how to fix that

**Comment by mrksharif** [comment]
Hi. I'm having the same problem decompiling .exe files. Did you finally solve the problem?
Thank you.
