### ISSUE TITLE
Error - Python 3.7

### ISSUE THREAD

**Issue by a1ch3mist** [countercept/python-exe-unpacker#5]
downloaded and just tried running "py python_exe_unpack.py" gives the following error on Win10:

----------------------------------------------

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\xdis\opcodes\base.py", line 209, in opcode_check
    assert all(item in opmap.items() for item in l['opmap'].items())
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python_exe_unpack.py", line 16, in <module>
    import uncompyle6
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\uncompyle6\__init__.py", line 52, in <module>
    from uncompyle6.main import decompile_file
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\uncompyle6\main.py", line 6, in <module>
    from uncompyle6.disas import check_object_path
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\uncompyle6\disas.py", line 26, in <module>
    from xdis.main import disassemble_file as xdisassemble_file
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\xdis\main.py", line 30, in <module>
    from xdis.op_imports import op_imports
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\xdis\op_imports.py", line 22, in <module>
    from xdis.opcodes import opcode_37 as opcode_37
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\xdis\opcodes\opcode_37.py", line 112, in <module>
    finalize_opcodes(l)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\xdis\opcodes\base.py", line 147, in finalize_opcodes
    opcode_check(l)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\xdis\opcodes\base.py", line 214, in opcode_check
    sys.version_info)
TypeError: not all arguments converted during string formatting

**Comment by MooseV2** [comment]
The `requirements.txt` file requests an outdated `uncompyle6` version.

Upgrading the package should fix this:

`pip install --upgrade uncompyle6`

**Comment by yinhetest** [comment]
I encountered the same problem using python3.7 version on win10, the update is meaningless.
